name: Deploy to Server

on:
  push:
    branches:
      - master  # or any other branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh ${{ secrets.USERNAME  }}@${{ secrets.HOST}}'bash -s' < .github/deploy.sh
