name: Deploy to Server

on:
  push:
    branches:
      - main  # or any other branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test secrests
      run: |
        echo ${{ secrets.USERNAME  }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh ${{ secrets.USERNAME  }}@${{ secrets.HOST}}'bash -s' < .github/deploy.sh
